# Feed forward NN

In [0]:
import numpy as np
from numpy.random import rand

In [0]:
input_ = np.array([[0.1, 0.2, 0.3, 0.4, 0.5]])

In [0]:
no_of_layers = 2
# No of neurons in input layer
no_of_neurons_input_layer = 5
# No of neurons in output layer
no_of_neurons_output_layer = 2

In [0]:
# Weight matrix btw input_layer to output_layer
#      On1.  On2
# In1  0.2    0.4
# In2  0.2    0.4
# In3  0.2    0.4
# In4  0.2    0.4
# In5  0.2    0.4
# (no_of_neurons_input_layer, no_of_neurons_output_layer) 5, 2
W = rand(no_of_neurons_input_layer, no_of_neurons_output_layer)

In [6]:
W

array([[0.83632167, 0.0408086 ],
       [0.25201456, 0.99060227],
       [0.97162051, 0.54620824],
       [0.99972827, 0.62973746],
       [0.65132817, 0.08844786]])

In [0]:
B = rand(1,no_of_neurons_output_layer)

In [19]:
B

array([[0.9690097 , 0.31597541]])

In [10]:
# All the components
input_, W, B

(array([[0.1, 0.2, 0.3, 0. , 4. , 0.5]]), array([[0.83632167, 0.0408086 ],
        [0.25201456, 0.99060227],
        [0.97162051, 0.54620824],
        [0.99972827, 0.62973746],
        [0.65132817, 0.08844786]]), array([[0.21292093, 0.24247711]]))

In [15]:
# How to find out outputs of neurons present in output layer
def activation_function(data):
  return np.tanh(data)

activation_function(np.matmul(input_,W) + B)

array([[0.877317  , 0.71855925]])

In [0]:

import tensorflow as tf

In [0]:
# 1 + 4
# A = 1
# B = 4

In [0]:
# Define the graph
# If you have single element A = tf.placeholder(shape=None,dtype)
# If you have array A = tf.placeholder(shape=[None],dtype)
# If you have matrix A = tf.placeholder(shape=[None,None],dtype)
A = tf.placeholder(shape=None,dtype=tf.float64)
B = tf.placeholder(shape=None,dtype=tf.float64)
res = A+B

In [23]:
# Execution of the graph

# create tensorflow session
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  
  # Define input values
  feed_dict = {A:1.0, B:4.0}
  
  # Executed the graph
  final_res = sess.run(res, feed_dict)
  print(final_res)

5.0


In [0]:
tf.reset_default_graph()

In [0]:
# Creating graph for FF NN
# input_ = np.array([[0.1, 0.2, 0.3, 0.4, 0.5]])
# classification:
# 0.1, 0.2, 0.3, 0.4, 0.5 --> 1,0
# 0.6, 0.2, 0.3, 0.7, 0.5 --> 0,1
input_ = tf.placeholder(shape=[None, 5], dtype=tf.float64)
output_input_layer = input_ # output of input layer
output_layer_res = tf.contrib.layers.fully_connected(output_input_layer, 2, activation_fn=tf.tanh)  # output layer

In [33]:
# create a session
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  # Define inputs
  feed_dict = {input_: [[0.1, 0.2, 0.3, 0.4, 0.5]] }
  
  # run the graph
  res = sess.run(output_layer_res, feed_dict)
  print(res)

[[-0.4010199  -0.34999524]]


In [34]:
#tf.tanh
y1 = 24
y2 = 12
y3 = 8
# sigmoid -- >  0 to 1   --> 1/ (1+e^(-x))
# tanh. --> -1  to. 1
np.tanh(24)

1.0

In [35]:
np.tanh(0.006)

0.005999928001036785

In [0]:
# Activation function
# Bias 