# We have seen how to do these experiments in excel sheets. Implement these tests using python. Please find the dataset in attached file.


# T-test

In [6]:
## Import the packages
import numpy as np
from scipy import stats
import pandas as pd
from numpy import genfromtxt


In [9]:
df=pd.read_csv("/home/alinemati/Yandex.Disk/Nirvana/database/tests_case_study.csv" )
df=df[['AWS response time','In House response time']]
 
N=df.shape[0]
N


30

In [10]:
df

AWS response time  In House response time
0                32.0                    96.0
1                16.0                    78.0
2                12.0                    64.0
3                34.0                    84.0
4                20.0                    70.0
5                26.0                    74.0
6                34.0                    80.0
7                32.0                    78.0
8                46.0                    90.0
9                38.0                    82.0
10               36.0                    80.0
11               16.0                    60.0
12               10.0                    54.0
13               50.0                    92.0
14               34.0                    76.0
15               44.0                    84.0
16               36.0                    76.0
17               34.0                    74.0
18               20.0                    60.0
19               52.0                    90.0
20               50.0                    88.0
21               48.0                    86.0
22               44.0                    82.0
23               32.0                    70.0
24               50.0                    86.0
25               42.0                    78.0
26               36.0                    72.0
27               36.0                    72.0
28               24.0                    60.0
29               22.0                    58.0

In [11]:
## Calculate the Standard Deviation
#Calculate the variance to get the standard deviation

#For unbiased max likelihood estimate we have to divide the var by N-1, and therefore the parameter ddof = 1
var_a = df['AWS response time'].var(ddof=1)
var_b = df['In House response time'].var(ddof=1)


var_a , var_b

(142.80919540229885, 119.36091954022987)

In [12]:
#std deviation
s = np.sqrt((var_a + var_b)/2)
s
print("std deviation" , s) 

std deviation 11.44923829218627


In [13]:

## Calculate the t-test
t = (df['AWS response time'].mean() - df['In House response time'].mean())/(s*np.sqrt(2/N))

print("Calculate the t-statistics : " , t)

Calculate the t-statistics :  -14.523244320161675


In [14]:
## Compare with the critical t-value
#Degrees of freedom
Degrees_of_freedom = 2*N - 2
print("Degrees of freedom:", Degrees_of_freedom)

Degrees of freedom: 58


In [19]:
#p-value after comparison with the t 
p = 1 - stats.t.cdf(t,df=Degrees_of_freedom)

print("p" , p)
print("t = " + str(t))
print("p = " + str(2*p))


p 1.0
t = -14.523244320161675
p = 2.0


In [16]:
### You can see that after comparing the t statistic with the critical t value (computed internally) 
# we get a good p value of 0.0005 and thus we reject the null hypothesis and thus it proves that the 
# mean of the two distributions are different and statistically significant.


## Cross Checking with the internal scipy function
t2, p2 = stats.ttest_rel(df['AWS response time'],df['In House response time'])
print("t = " + str(t2))
print("p = " + str(p2))

t = -32.85218914560019
p = 1.6975043621672066e-24


In [18]:
print('p-values',p2)
if p2 < 0.05:    # alpha value is 0.05 or 5%
   print(" We are rejecting null hypothesis")
else:
  print("We are accepting null hypothesis")

p-values 1.6975043621672066e-24
 We are rejecting null hypothesis


#  Anova Test

In [8]:
import pandas as pd 
import scipy.stats as stats
data=pd.read_csv("/home/alinemati/Yandex.Disk/Nirvana/database/tests_case_study1.csv" )

data.head()
data.tail()

index  Server1  Server2  Server3
9      10       12       14       13
10     11       12       12       14
11     12       15       14       13
12     13       11       14       13
13     14       12       14       14

In [17]:
d1 = data.Server1
d2 = data.Server2
d3 = data.Server3


In [18]:
d1.describe()

count    14.000000
mean     12.571429
std       1.650841
min      11.000000
25%      11.250000
50%      12.000000
75%      14.250000
max      15.000000
Name: Server1, dtype: float64

In [19]:
d2.describe()

count    14.000000
mean     13.214286
std       1.121714
min      12.000000
25%      12.000000
50%      14.000000
75%      14.000000
max      15.000000
Name: Server2, dtype: float64

In [20]:
d3.describe()

count    14.000000
mean     13.071429
std       0.828742
min      12.000000
25%      12.250000
50%      13.000000
75%      14.000000
max      14.000000
Name: Server3, dtype: float64

In [21]:
stats.shapiro(d1), stats.shapiro(d2), stats.shapiro(d3) 

((0.743291437625885, 0.0010778249707072973),
 (0.7424878478050232, 0.0010558408685028553),
 (0.8104488849639893, 0.00674004852771759))

In [22]:
# Levene variance test  
stats.levene(d1, d2, d3)

LeveneResult(statistic=0.9075471698113203, pvalue=0.41186429693754756)

In [23]:
# Apply one way ANOVA by calling the f_oneway() method¶
F, p = stats.f_oneway(d1, d2, d3)
print('F statistic = {:5.3f} and probability p = {:5.3f}'.format(F, p)) 

F statistic = 1.025 and probability p = 0.368


In [27]:
# apply ttest_indep()
t, p = stats.ttest_ind(d1, d2)
print('Server1 vs Server2: \t', t, p)

t, p = stats.ttest_ind(d1, d3)
print('Server1 vs Server3: \t', t, p)

t, p = stats.ttest_ind(d2, d3)
print('Server2 vs Server3: \t', t, p)

Server1 vs Server2 	: -1.2051613141415742 0.23899586563980885
Server1 vs Server3: 	 -1.0128005209961697 0.32048844485923544
Server2 vs Server3: 	 0.3832657764100919 0.704638624357981


# CHI-Square Test 

In [29]:

# chi-squared test with similar proportions

# chi-squared test with similar proportions
from scipy.stats import chi2_contingency
from scipy.stats import chi2
# contingency table
table =data
table

index  Server1  Server2  Server3
0       1       11       12       12
1       2       12       14       13
2       3       15       12       14
3       4       11       12       12
4       5       12       14       13
5       6       15       15       14
6       7       12       12       12
7       8       15       14       12
8       9       11       12       14
9      10       12       14       13
10     11       12       12       14
11     12       15       14       13
12     13       11       14       13
13     14       12       14       14

In [30]:
stat, p, dof, expected = chi2_contingency(table)
print('dof=%d' % dof)
print(expected)

dof=39
[[ 5.82434515  9.76271186 10.26194145 10.15100154]
 [ 6.63328197 11.11864407 11.68721109 11.56086287]
 [ 7.11864407 11.93220339 12.54237288 12.40677966]
 [ 6.30970724 10.57627119 11.11710324 10.99691834]
 [ 7.11864407 11.93220339 12.54237288 12.40677966]
 [ 8.08936826 13.55932203 14.25269646 14.09861325]
 [ 6.9568567  11.66101695 12.25731895 12.1248074 ]
 [ 7.92758089 13.28813559 13.96764253 13.81664099]
 [ 7.4422188  12.47457627 13.11248074 12.97072419]
 [ 7.92758089 13.28813559 13.96764253 13.81664099]
 [ 7.92758089 13.28813559 13.96764253 13.81664099]
 [ 8.73651772 14.6440678  15.39291217 15.22650231]
 [ 8.25115562 13.83050847 14.53775039 14.38058552]
 [ 8.73651772 14.6440678  15.39291217 15.22650231]]


In [35]:

# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))

if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
    
    # interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

probability=0.950, critical=54.572, stat=27.193
Independent (fail to reject H0)
significance=0.050, p=0.923
Independent (fail to reject H0)
